version: '3'
services:
  postgres:
    container_name: itservice-db
    image: "postgres:15"
    restart: always
    ports:
      - "5435:5435"
    environment:
      POSTGRES_DB: itservice
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: omonov2006
  crm-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: crm-app
    ports:
      - "8084:8084"
    depends_on:
      - postgres
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://itservice-db:5432/itservice
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: omonov2006

volumes:
  postgres-data:
