version: '3.8'

services:
  postgres:
    image: postgres:12.7-alpine
    container_name: postgres-db
    environment:
      POSTGRES_DB: crmuchun
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: omonov2006
    ports:
      - "5434:5434"
    command: ["postgres", "-c", "log_statement=all"]
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

  crm-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: crm-app
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/crmuchun
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: omonov2006
      SPRING_JPA_SHOW_SQL: "true"
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      SPRING_SERVLET_MULTIPART_ENABLED: "true"
      SPRING_SERVLET_MULTIPART_MAX_FILE_SIZE: 10MB
      SPRING_SERVLET_MULTIPART_MAX_REQUEST_SIZE: 10MB
      SPRING_SERVLET_MULTIPART_FILE_SIZE_THRESHOLD: 0
      SPRING_SQL_INIT_MODE: always

volumes:
  postgres-data:

